### ISSUE TITLE
missing ios and android folders

### ISSUE THREAD

**Issue by faceyspacey** [efkan/rndrawer-implemented-rnrouter#1]
How should I get this to run (iOS) without the xcodeproj?

**Comment by efkan** [comment]
Hi, 
The files have only React-Native code. Actually I don't have an iOS to test out it. But it should be run by using the following instructions.

So, to run the code; 
- First `react-native init myDrawerExample` command should be run on the console. 
- Secondly `index.ios.js` file and `src` folder are copied into the new `myDrawerExample` project. And `AppRegistry.registerComponent('reactNativeRouterFluxSample', () => Example);` line of `index.ios.js` file should be changed as `AppRegistry.registerComponent('myDrawerExample', () => Example);`
- Then run the command of `npm i react-native-button --save && npm i react-native-drawer --save && npm i react-native-router-flux --save`. If `redux` will be used, the command of `npm i redux --save && npm i react-redux --save` should be run too.
- Finally, [official site](https://facebook.github.io/react-native/docs/getting-started.html#quick-start) says that; "Open ios/myDrawerExample.xcodeproj and hit run in Xcode".

**Comment by faceyspacey** [comment]
ok, u can close this, i was just saying most examples are all self-contained, i.e. come bundled with everything so u dont have to add it to an existing app. That's how the best examples are--because it makes it super easy for new React Native users to just test it out without hoping it will just work in an existing app.

**Comment by efkan** [comment]
Ok, I see. Good luck..
