### ISSUE TITLE
Problem when click "Drawer" button.

### ISSUE THREAD

**Issue by luisfuertes** [efkan/rndrawer-implemented-rnrouter#10]
Hi, i am developing my project with your template. I always run it on emulator and it run perfec. But now i try to run on real device (Android&iOS) and when i press button on drawer, it have a few secs of lag before new View load.

Maybe some dependencie version cause conflict with drawer or react-native-router-flux?

My dependencies:
"dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-button": "^1.4.2",
    "react-native-calendar-picker": "^2.4.0",
    "react-native-datepicker": "^1.1.0",
    "react-native-drawer": "^1.16.7",
    "react-native-lightbox": "^0.5.1",
    "react-native-router-flux": "^2.2.7",
    "react-native-scrollable-tab-view": "^0.4.1",
    "react-native-simple-radio-button": "^2.0.1",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-thunk": "^2.0.1"
  },
  "devDependencies": {
    "babel-eslint": "^4.1.8",
    "eslint": "^1.10.3",
    "eslint-plugin-react": "^3.16.1",
    "eslint-plugin-react-native": "^0.5.0"
  }

Thanks!

**Comment by efkan** [comment]
Unfortunately, I had not encountered an issue like this on my phone. 
Could you please check `console.log()` lines in your app. And if they exist mark them as comment line.
That way is save me when I was experiencing a slowing issue.

**Comment by luisfuertes** [comment]
It fix update all components to last version :S 

  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1",
    "react-native-button": "^1.5.0",
    "react-native-calendar-picker": "^2.6.0",
    "react-native-datepicker": "^1.1.0",
    "react-native-drawer": "^2.2.2",
    "react-native-lightbox": "^0.6.0",
    "react-native-router-flux": "^2.3.1",
    "react-native-scrollable-tab-view": "^0.4.2",
    "react-native-simple-radio-button": "^2.0.2",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^4.1.8",
    "eslint": "^1.10.3",
    "eslint-plugin-react": "^3.16.1",
    "eslint-plugin-react-native": "^0.5.0"
  }

Thanks for your time @efkan

**Comment by efkan** [comment]
In my latest trying `react-native-drawer`, it didn't work properly. I guess it got fixed. Enjoy it!
I'm closing the issue..
