### ISSUE TITLE
Using image in title ?

### ISSUE THREAD

**Issue by EugeneLiang** [efkan/rndrawer-implemented-rnrouter#11]
Hi good day!

Firstly, AWESOME job with this example! Really solved major headaches! 

I was just wondering if it is possible to use an image for the title?

For example: 

`<Route name='Home' component={ScreenHome} schema='home' title={this.renderLogo} />`

and `renderLogo` looks like this:

`renderLogo = () => {
        return (
            <Image
                source={require('../images/icons/logo.png')}
                style={{height: 24, width: 24}}
            />
        )
    };
`

I've tried the above out, but on Home screen, I do not see any logo rendered. I did not receive any errors too. 

I was wondering if you have any insights as to how to use images in titles?

Cheers and thanks again!

**Comment by efkan** [comment]
Hi,

> Using image in title? 

Sure. I've written an example the below. Also you might check `renderTitle` property out from [here](https://github.com/aksonov/react-native-router-flux/tree/2.x#route) to do that.

```
renderTitle = () => {
    return (
        <View style={styles.title}>
            <Text>{'Awesome Title'}</Text>
        </View>
    )
};
```

then 

```
<Route 
    name='RouteName' 
    renderTitle={this.renderTitle}
/>
```

Good luck!

**Comment by EugeneLiang** [comment]
cool thank you!
