### ISSUE TITLE
Center NavBar Image on Android

### ISSUE THREAD

**Issue by luisfuertes** [efkan/rndrawer-implemented-rnrouter#12]
Im trying to center navBar image. on iOS image render center perfect, but on android i cant do it.

My image code: 

```
renderNavigatorTitleImage = () => {
        return (
            <View style={{
                flex: 1,
                alignItems: 'center',
                justifyContent: 'center',
            }}>
                <Image
                    source={require('./Resources/logo2.png')}
                    style={{ height: 30, width: 76}}
                    resizeMode="cover"
                />
            </View>
        )
    };
```

and in set on <Route> element, on "renderTitle" prop.

navBar style:

```
    navBar: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E12518',
    },
```

Image always appear on top left. I try to use Dimensions, etc but i cant set on the mid.
Some idea?

**Comment by efkan** [comment]
Hello,

Sorry for the late response.

Although navigation bar image at center is not correct you could do that:

```
<Router
  navigationBarStyle={Navigator.NavigationBar.StylesIOS}
/>
```

The source is [here](https://github.com/aksonov/react-native-router-flux/tree/2.x#route)

I recommend checking [this](https://github.com/exponentjs/ex-navigator/issues/24) out at first.

Good luck.
