### ISSUE TITLE
Auto change screens using componentDidMount ?

### ISSUE THREAD

**Issue by EugeneLiang** [efkan/rndrawer-implemented-rnrouter#13]
Hi there, 

May I know if it is possible to navigate without using 
`onPress` ?

For example, in Login.js, we use `render()` this:
`<Button onPress={Actions.Drawer}>Login</Button>` 
and that in order to go to the `Drawer` screen we need to 
tap on the button

Is there a way to navigate to the `Drawer` screen when the Login screen loads?
For example navigate to `Drawer` programmatically via `componentDidMount` ?

Cheers.

**Comment by efkan** [comment]
This issue is obsolete.

@EugeneLiang , if you overcome this issue, explaining how you managed it would be great!

Good luck..
