### ISSUE TITLE
Failed to install the requested application

### ISSUE THREAD

**Issue by mhammedmohie** [efkan/rndrawer-implemented-rnrouter#16]
Hello, 
I'm a react-native beginner and was trying to build the project to understand how the Side menu and  Navigation work together in the app.
I downloaded the project
made npm install in the terminal
then when I tried to run on the iOS, I got error 

```
** BUILD FAILED **


The following commands produced analyzer issues:
	Analyze RCTLocationObserver.m

(1 command with analyzer issues)

The following build commands failed:
	CompileC /Users/mohammedelgohary/Downloads/rndrawer-implemented-rnrouter-master\ 2/ios/build/Build/Intermediates/RCTSettings.build/Debug-iphonesimulator/RCTSettings.build/Objects-normal/x86_64/RCTSettingsManager.o RCTSettingsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/reactNativeRouterFluxSample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reactNativeRouterFluxSample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by efkan** [comment]
Hello,

Unfortunately I don't have an OS X. Because of this I just recommend trying installation steps if you didn't before. I remember that these steps had worked for others.

https://github.com/efkan/rndrawer-implemented-rnrouter#installation

**Comment by efkan** [comment]
If you still interest in this example and your issue continue please specify in this page to re-open this issue.

Someone could manage to run this example on iOS you may find [overhere](https://github.com/efkan/rndrawer-implemented-rnrouter/issues/17)

Have a beautiful day!
