### ISSUE TITLE
Unhandled JS Exception: [react-native-router-flux] unique key should be defined

### ISSUE THREAD

**Issue by harish220** [efkan/rndrawer-implemented-rnrouter#17]
I am getting "[react-native-router-flux] unique key should be defined error." and in console "Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Example`.
[react-native-router-flux] unique key should be defined 
Unhandled JS Exception: [react-native-router-flux] unique key should be defined " 

I have followed exact below steps:
1.Run the command of react-native init reactNativeRouterFluxSample & cd reactNativeRouterFluxSample
2.Then npm i --save react-native-drawer@1.16.7 & npm i --save react-native-router-flux@2.2.7 & npm i --save react-native-button@1.4.2
3.Then copy src folder and index.ios.js file of rndrawer-implemented-rnrouter into the new initiated project.
4.Finally, official site says that; "Open ios/reactNativeRouterFluxSample.xcodeproj and hit run in Xcode".

Below is the render method in Example.js

`render() {
								return (
												<Router name='root'>
																<Schema name='boot' sceneConfig={Navigator.SceneConfigs.FloatFromRight} hideNavBar type='replace' // When type='replace' is existing Actions.pop never work
																/>
																<Route name='Login' component={Login} schema='boot' initial title="Welcome"/>
																<Route name='Register' component={Register} hideNavBar title="Register Screen"/>
																<Route name='Drawer' hideNavBar type='reset'>
																				<SideDrawer
																								ref={c => {
																								c
																												? this.drawer = c.drawer
																												: this.drawer
																				}}>
																								{/*Nested Routes are used for to manage the navbar cases (Route[Home] \ Router \ Route[Home_] )
						React-Native-Reouter-Flux actions use the route names.*/}
																								<Router
																												name='drawerRoot'
																												sceneStyle={styles.routerScene}
																												navigationBarStyle={styles.navBar}
																												titleStyle={styles.navTitle}>
																												<Schema
																																name='home'
																																sceneConfig={Navigator.SceneConfigs.FloatFromRight}
																																hideNavBar={false}
																																renderLeftButton={this.renderMenuButton}/>
																												<Schema
																																name='interior'
																																sceneConfig={Navigator.SceneConfigs.FloatFromRight}
																																hideNavBar={false}
																																renderLeftButton={this.renderBackButton}/>
																												<Route name='Home' component={ScreenHome} schema='home' title='Home'/>
																												<Route name='Screen1' component={Screen1} schema='interior' title='Screen1'/>
																												<Route name='Screen2' component={Screen2} schema='interior' title='Screen2'/>
																								</Router>
																				</SideDrawer>
																</Route>
												</Router>
								);
				}`

**Comment by efkan** [comment]
I guess this issue is regarding with `breaking-changes` in `react-native` upgrades.

I had changed some files when it needs. The files I use might be overcome this issue.

Could you please try to replace [these](https://github.com/efkan/rndrawer-implemented-rnrouter/blob/master/change_these_folders_with_their_originals.zip) folders with their originals in `node_modules` folder?

**Comment by harish220** [comment]
Thanks for replay, I have replaced the folders in node modules folder, still am getting below issue:
**Component is not defined**
Running application reactNativeRouterFluxSample ({
    initialProps =     {
    };
    rootTag = 1;
})
Module AppRegistry is not a registered callable module (calling runApplication)
Unhandled JS Exception: Component is not defined
Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by harish220** [comment]
Fixed, replaced import React from 'react' with import React, { Component,} from 'react'; in ActionSheet.ios.js in @exponent.
