### ISSUE TITLE
Override/finding taptoclose event outside drawer

### ISSUE THREAD

**Issue by harish220** [efkan/rndrawer-implemented-rnrouter#18]
Hi,

When user tap on outside drawer, drawer will closed with line of code "tapToClose={true}",
In the same time I need to trigger method here, because PFA screen shot as per screen shot I need to change back arrow button to menu button.

![simulator screen shot 15-feb-2017 2 26 58 pm](https://cloud.githubusercontent.com/assets/120794/22972002/cd61c5f0-f39d-11e6-8016-c67d711b51e5.png)

**Comment by efkan** [comment]
@harish220 ,

In fact, this is just a example. I think asking on components pages (`react-native-drawer` and `react-native-router-flux`) may provide to reach more people (real creators and contributors).

For instance, you might ask your triggering question over here: https://github.com/root-two/react-native-drawer/issues  

And changing arrow icon to a menu icon is only button icon changing. Unfortunately mobile development (react-native) is not as simple as web development.

To change arrow icon I use my own button component. But it's not needed I wrote this info if some props is not equal to `react-native` button components.

This is my implementation:

```
import MaterialIcons from 'react-native-vector-icons/MaterialIcons'

renderMenuButton = () => {
	return (
		<Button
			style={{flex: 1}}
			icon={<MaterialIcons name="menu" size={24} />}
			onPress={() => this.drawer.open()}
		/>
	)
};
```

Then I implement renderMenuButton method as below but my implementation is a bit complex:

```
<Route name='Home' hideNavBar >
	<Router sceneStyle={styles.scene}>
		<Route name='Home_' component={containers.Screens.Home}
			title={"Home"} schema='page'
			renderLeftButton={this.renderMenuButton}
		/>
	</Router>
</Route>
```

You might be useful asking a question on http://stackoverflow.com/ .
Also https://github.com/aksonov/react-native-router-flux for `react-native-router-flux`.

And keep in mind this example uses the old version both of two components.

Good luck...
