### ISSUE TITLE
How to add a top left nav button, which opens the drawer

### ISSUE THREAD

**Issue by paulwcy** [efkan/rndrawer-implemented-rnrouter#4]
Hi,

Still quite new to react native... Was just wondering if you could add in your example, how I can add a top left navigation button which toggles the open/close of the drawer.

Thanks.

**Comment by efkan** [comment]
Hi,

I've done by using [renderLeftButton ](https://github.com/aksonov/react-native-router-flux#configuration)prop of React-Native-Router-Flux.

The sample below could be useful;

```
...
renderMenuButton = () => {
    return (
        <TouchableOpacity
            style={styles.leftButtonContainer}
            onPress={() => this.drawer.open()}
        >
            <Image
                source={require('image!ic_menu_white_24dp')}
                style={{height: 24, width: 24, opacity: 0.87}}
            />
        </TouchableOpacity>
    )
};    
...
render() {
...
    <Route
        name='Home'
        title='Home screen'
        component={HomeComponent}
        renderLeftButton={this.renderMenuButton} 
        initial
    />
...
}
```

**Comment by paulwcy** [comment]
Hi @efkan, thanks for the code sample.
I've added the code above, but still unable to get the drawer to open.

Got an error at `this.drawer` being null. Looks like `this.state.drawer` is initialised but there are no assignments to it. Was it supposed to be passed back from SideDrawer.js?

**Comment by paulwcy** [comment]
I got it working by passing props...

```
render() {
...
<SideDrawer addDrawer={this.addDrawer}>
...
</SideDrawer>
...

    addDrawer = (newdrawer) => {
        this.setState({drawer : newdrawer})
    };

    renderMenuButton = () => {
        return (
            <TouchableOpacity
                style={styles.leftButtonContainer}
                onPress={() => this.state.drawer.open()}
            >
                <Text>Menu</Text>
            </TouchableOpacity>
        )
    };

```

Then in SideDrawer, declared Drawer as

```
    <Drawer ref={c => this.drawer = c}   .....
```

and added `componentDidMount()`

```
  componentDidMount() {
    this.props.addDrawer(this.drawer)
  }
```

**Comment by efkan** [comment]
@paulwcy ,

You're right. Sorry for the information lacks in my answer.
The example was not clear.  Therefore I've refactored the code. Remembering and refocatoring took almost my all day.

Now it looks more clear.

I'm closing the issue but you feel free to ask about something else.
