### ISSUE TITLE
I can't do code run

### ISSUE THREAD

**Issue by luisfuertes** [efkan/rndrawer-implemented-rnrouter#7]
Hi, 

Your example is perfect for my project.

But i do:
1. git clone (repo link)
2. npm install (on project route)

And when i open ios project on Xcode and run:
![captura de pantalla 2016-04-26 a las 18 18 32](https://cloud.githubusercontent.com/assets/18212615/14825948/267b2834-0bdc-11e6-9055-a43f8cce5d51.png)

Thanks!

**Comment by efkan** [comment]
Hi,

I don't have an Apple product. For this reason I cannot give a complete solutions. Nevertheless the steps below may solve the problem;
1. Run the command of `react-native init reactNativeRouterFluxSample & cd reactNativeRouterFluxSample`
2. Then `npm i --save react-native-drawer@1.16.7 & npm i --save react-native-router-flux@2.2.7 & npm i --save react-native-button@1.4.2`
3. Then copy `src` folder and `index.ios.js` file of rndrawer-implemented-rnrouter into the new initiated project.
4. Finally, [official site](https://facebook.github.io/react-native/docs/getting-started.html#quick-start) says that; "Open ios/reactNativeRouterFluxSample.xcodeproj and hit run in Xcode".

**Comment by luisfuertes** [comment]
That works!

You can add to Readme of your repository.

Thanks!

Last question. For replace all scenes like home, with "Menu" button on corner always. How can i do?

**Comment by efkan** [comment]
To see implementing a menu button could you check [this](https://github.com/efkan/rndrawer-implemented-rnrouter/issues/4) out. If you have another question, sure, you can write here.

**Comment by luisfuertes** [comment]
I'm trying to set navigation bar style on "Register" screen.

I think i must set on < Router > Item, but i cant create a Router child of Root. for set "Register" Navigation Bar style.

Im seing the react-native-router-flux documentation, but it use "Scene", not "Route" items.

Can u help me?

**Comment by efkan** [comment]
The current docs of the RNRF is for version 3.X.
But you can find the version 2.X docs from [here](https://github.com/aksonov/react-native-router-flux/tree/2.x).

On the other hand, if you want to show the navbar you just remove `hideNavBar` keyword in [this line](https://github.com/efkan/rndrawer-implemented-rnrouter/blob/master/src/Example.js#L98).

**Comment by luisfuertes** [comment]
Thanks!

You know what is that? Appear sometimes.
![captura de pantalla 2016-04-28 a las 9 28 25](https://cloud.githubusercontent.com/assets/18212615/14878407/aa135ee4-0d23-11e6-9a11-daeed880237f.png)

**Comment by efkan** [comment]
I don't know. I have never seen this error.

Good luck..

**Comment by luisfuertes** [comment]
Hahaha ok no problem,

Thanks for all!
