### ISSUE TITLE
Connect with Redux

### ISSUE THREAD

**Issue by luisfuertes** [efkan/rndrawer-implemented-rnrouter#9]
Hi, im trying to implement Redux on my project.

When i uncomment Redux Section, i comment line:
`import { Router, Route, Schema, Actions, } from 'react-native-router-flux'`

But terminal:

> Could not find "store" in either the context or props of "Connect(Router)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Router)".

Can you help me?

**Comment by luisfuertes** [comment]
Ok, wrapping the "root" `<Router>` in `<Provider store={store}> </Provider>` runs.

**Comment by efkan** [comment]
Hi,

I assume that you have never use Redux yet. 
A common usage of Redux store is the wrapping the root App (JSX expression).

Some links regarding Redux usage with RNRouter;
https://github.com/aksonov/react-native-router-flux/tree/2.x#reduxflux-support
http://redux.js.org/docs/basics/ExampleTodoList.html
https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree?series=getting-started-with-redux

Ohh.. You've figured out it! :+1: 

Good luck...

**Comment by luisfuertes** [comment]
Thanks!
